/// <autosync enabled="true" />
/// <reference path="git/Commit.js" />
/// <reference path="git/File.js" />
/// <reference path="git/Org3 - Copy.js" />
/// <reference path="git/Org3.js" />
/// <reference path="git/Repository.js" />
/// <reference path="main.js" />
/// <reference path="main_version2.js" />
/// <reference path="main_version3.js" />
/// <reference path="server.js" />
/// <reference path="../UnitTest.js" />
